add cache in logo creation
himmel520/media-service pull request #13
Opened 2024-10-27 17:49 UTC by Dev-cmyser

2024-10-27 23:57 UTC, himmel520 commented on internal/controller/http/logo.go
добавила в задачи

2024-10-28 00:02 UTC, himmel520 requested changes
не тот кэш(adv, вместо лого)

2024-10-28 00:02 UTC, himmel520 commented on internal/usecase/logo.go
почему adv, если это кэш для лого

2024-10-28 00:02 UTC, himmel520 commented on internal/usecase/usecase.go
тоже самое это лого, а не adv

2024-10-28 06:29 UTC, Dev-cmyser commented on internal/usecase/logo.go
пока это draft, eще работаю над этим пр
но вообще в планах уйти от этого разделения

2024-10-28 12:58 UTC, himmel520 commented on internal/infrastructure/cache/redis/redis.go
> +	advsByte, err := json.Marshal(advs)
если кэш универсален, то другое название без конкретик

2024-10-29 13:05 UTC, himmel520 commented on internal/controller/http/error.go
> +var (
Вынеси ошибки контролера в controller/error.go
package controller

import "errors"

var (
	ErrInvalidID = errors.New("invalid id")
	ErrEmptyAuthHeader = errors.New("authorization header is missing")
	ErrInvalidAuthHeader = errors.New("authorization header is invalid")
	ErrForbidden = errors.New("you don't have access to this resource")
)

тогда будет
ErrInvalidID         = NewHttpError(controller.ErrInvalidID, http.StatusBadRequest)

2024-10-29 13:05 UTC, himmel520 commented on internal/controller/errors.go
Оставь эти ошибки, а потом импортируй куда надо

2024-10-29 13:05 UTC, himmel520 commented on internal/controller/http/logo_test.go
> +			// mockLogoUsecase.AssertExpectations(t)
лишний комент

2024-10-29 13:07 UTC, Dev-cmyser commented on internal/controller/http/error.go
> +var (
ага, хорошо

2024-10-29 13:22 UTC, merged